### ISSUE TITLE
Update the test runner to for overriding the new `skip` directives

### ISSUE THREAD

**Issue by glennj** [exercism/tcl-test-runner#6]
I'm revamping the Tcl test files, which will add `skip` directives (https://github.com/exercism/tcl/pull/205). Setting the `RUN_ALL` env variable will override that behaviour. The `run.sh` file will have to be updated to accomodate that.

**Comment by ErikSchierboom** [comment]
> The run.sh file will have to be updated to accomodate that.

One easy way to do this would be to just bake it into the [Docker image](https://github.com/exercism/tcl-test-runner/blob/main/Dockerfile) using the [`ENV` instruction](https://docs.docker.com/engine/reference/builder/#env).
